spring:
  application:
    name: spring-cloud-example-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/
server:
  port: 8090